export default {
  "login": "bliss-armah",
  "id": 70046492,
  "node_id": "MDQ6VXNlcjcwMDQ2NDky",
  "avatar_url": "https://avatars.githubusercontent.com/u/70046492?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/bliss-armah",
  "html_url": "https://github.com/bliss-armah",
  "followers_url": "https://api.github.com/users/bliss-armah/followers",
  "following_url": "https://api.github.com/users/bliss-armah/following{/other_user}",
  "gists_url": "https://api.github.com/users/bliss-armah/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/bliss-armah/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/bliss-armah/subscriptions",
  "organizations_url": "https://api.github.com/users/bliss-armah/orgs",
  "repos_url": "https://api.github.com/users/bliss-armah/repos",
  "events_url": "https://api.github.com/users/bliss-armah/events{/privacy}",
  "received_events_url": "https://api.github.com/users/bliss-armah/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Bliss ",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": "Frontend Developer React.JS",
  "twitter_username": null,
  "public_repos": 9,
  "public_gists": 0,
  "followers": 4,
  "following": 2,
  "created_at": "2020-08-22T03:28:58Z",
  "updated_at": "2023-01-19T21:33:44Z"
}